const mainFunctions = require("./main");

module.exports = {
  // main Database
  // Post Db Object
  dbGetPost: mainFunctions.dbGetPost,
  dbCreatePost: mainFunctions.dbCreatePost,
  dbUpdatePost: mainFunctions.dbUpdatePost,
  dbDeletePost: mainFunctions.dbDeletePost,
  dbListPosts: mainFunctions.dbListPosts,
  createPost: mainFunctions.createPost,
  getIdListOfPostByField: mainFunctions.getIdListOfPostByField,
  getPostById: mainFunctions.getPostById,
  getPostAggById: mainFunctions.getPostAggById,
  getPostListByQuery: mainFunctions.getPostListByQuery,
  getPostStatsByQuery: mainFunctions.getPostStatsByQuery,
  getPostByQuery: mainFunctions.getPostByQuery,
  updatePostById: mainFunctions.updatePostById,
  updatePostByIdList: mainFunctions.updatePostByIdList,
  updatePostByQuery: mainFunctions.updatePostByQuery,
  deletePostById: mainFunctions.deletePostById,
  deletePostByQuery: mainFunctions.deletePostByQuery,
  // Comment Db Object
  dbGetComment: mainFunctions.dbGetComment,
  dbCreateComment: mainFunctions.dbCreateComment,
  dbUpdateComment: mainFunctions.dbUpdateComment,
  dbDeleteComment: mainFunctions.dbDeleteComment,
  dbListComments: mainFunctions.dbListComments,
  createComment: mainFunctions.createComment,
  getIdListOfCommentByField: mainFunctions.getIdListOfCommentByField,
  getCommentById: mainFunctions.getCommentById,
  getCommentAggById: mainFunctions.getCommentAggById,
  getCommentListByQuery: mainFunctions.getCommentListByQuery,
  getCommentStatsByQuery: mainFunctions.getCommentStatsByQuery,
  getCommentByQuery: mainFunctions.getCommentByQuery,
  updateCommentById: mainFunctions.updateCommentById,
  updateCommentByIdList: mainFunctions.updateCommentByIdList,
  updateCommentByQuery: mainFunctions.updateCommentByQuery,
  deleteCommentById: mainFunctions.deleteCommentById,
  deleteCommentByQuery: mainFunctions.deleteCommentByQuery,
  // Vote Db Object
  dbGetVote: mainFunctions.dbGetVote,
  dbCreateVote: mainFunctions.dbCreateVote,
  dbUpdateVote: mainFunctions.dbUpdateVote,
  dbDeleteVote: mainFunctions.dbDeleteVote,
  dbListVotes: mainFunctions.dbListVotes,
  createVote: mainFunctions.createVote,
  getIdListOfVoteByField: mainFunctions.getIdListOfVoteByField,
  getVoteById: mainFunctions.getVoteById,
  getVoteAggById: mainFunctions.getVoteAggById,
  getVoteListByQuery: mainFunctions.getVoteListByQuery,
  getVoteStatsByQuery: mainFunctions.getVoteStatsByQuery,
  getVoteByQuery: mainFunctions.getVoteByQuery,
  updateVoteById: mainFunctions.updateVoteById,
  updateVoteByIdList: mainFunctions.updateVoteByIdList,
  updateVoteByQuery: mainFunctions.updateVoteByQuery,
  deleteVoteById: mainFunctions.deleteVoteById,
  deleteVoteByQuery: mainFunctions.deleteVoteByQuery,
  // PollOption Db Object
  dbGetPolloption: mainFunctions.dbGetPolloption,
  dbCreatePolloption: mainFunctions.dbCreatePolloption,
  dbUpdatePolloption: mainFunctions.dbUpdatePolloption,
  dbDeletePolloption: mainFunctions.dbDeletePolloption,
  dbListPolloptions: mainFunctions.dbListPolloptions,
  createPollOption: mainFunctions.createPollOption,
  getIdListOfPollOptionByField: mainFunctions.getIdListOfPollOptionByField,
  getPollOptionById: mainFunctions.getPollOptionById,
  getPollOptionAggById: mainFunctions.getPollOptionAggById,
  getPollOptionListByQuery: mainFunctions.getPollOptionListByQuery,
  getPollOptionStatsByQuery: mainFunctions.getPollOptionStatsByQuery,
  getPollOptionByQuery: mainFunctions.getPollOptionByQuery,
  updatePollOptionById: mainFunctions.updatePollOptionById,
  updatePollOptionByIdList: mainFunctions.updatePollOptionByIdList,
  updatePollOptionByQuery: mainFunctions.updatePollOptionByQuery,
  deletePollOptionById: mainFunctions.deletePollOptionById,
  deletePollOptionByQuery: mainFunctions.deletePollOptionByQuery,
  // PostMedia Db Object
  dbGetPostmedia: mainFunctions.dbGetPostmedia,
  dbAddPostmedia: mainFunctions.dbAddPostmedia,
  dbUpdatePostmedia: mainFunctions.dbUpdatePostmedia,
  dbDeletePostmedia: mainFunctions.dbDeletePostmedia,
  dbListPostmedia: mainFunctions.dbListPostmedia,
  createPostMedia: mainFunctions.createPostMedia,
  getIdListOfPostMediaByField: mainFunctions.getIdListOfPostMediaByField,
  getPostMediaById: mainFunctions.getPostMediaById,
  getPostMediaAggById: mainFunctions.getPostMediaAggById,
  getPostMediaListByQuery: mainFunctions.getPostMediaListByQuery,
  getPostMediaStatsByQuery: mainFunctions.getPostMediaStatsByQuery,
  getPostMediaByQuery: mainFunctions.getPostMediaByQuery,
  updatePostMediaById: mainFunctions.updatePostMediaById,
  updatePostMediaByIdList: mainFunctions.updatePostMediaByIdList,
  updatePostMediaByQuery: mainFunctions.updatePostMediaByQuery,
  deletePostMediaById: mainFunctions.deletePostMediaById,
  deletePostMediaByQuery: mainFunctions.deletePostMediaByQuery,
};
