const mainFunctions = require("./main");

module.exports = {
  // main Database
  // SystemMetric Db Object
  createSystemMetric: mainFunctions.createSystemMetric,
  getIdListOfSystemMetricByField: mainFunctions.getIdListOfSystemMetricByField,
  getSystemMetricById: mainFunctions.getSystemMetricById,
  getSystemMetricAggById: mainFunctions.getSystemMetricAggById,
  getSystemMetricListByQuery: mainFunctions.getSystemMetricListByQuery,
  getSystemMetricStatsByQuery: mainFunctions.getSystemMetricStatsByQuery,
  getSystemMetricByQuery: mainFunctions.getSystemMetricByQuery,
  updateSystemMetricById: mainFunctions.updateSystemMetricById,
  updateSystemMetricByIdList: mainFunctions.updateSystemMetricByIdList,
  updateSystemMetricByQuery: mainFunctions.updateSystemMetricByQuery,
  deleteSystemMetricById: mainFunctions.deleteSystemMetricById,
  deleteSystemMetricByQuery: mainFunctions.deleteSystemMetricByQuery,
  // ErrorLog Db Object
  createErrorLog: mainFunctions.createErrorLog,
  getIdListOfErrorLogByField: mainFunctions.getIdListOfErrorLogByField,
  getErrorLogById: mainFunctions.getErrorLogById,
  getErrorLogAggById: mainFunctions.getErrorLogAggById,
  getErrorLogListByQuery: mainFunctions.getErrorLogListByQuery,
  getErrorLogStatsByQuery: mainFunctions.getErrorLogStatsByQuery,
  getErrorLogByQuery: mainFunctions.getErrorLogByQuery,
  updateErrorLogById: mainFunctions.updateErrorLogById,
  updateErrorLogByIdList: mainFunctions.updateErrorLogByIdList,
  updateErrorLogByQuery: mainFunctions.updateErrorLogByQuery,
  deleteErrorLogById: mainFunctions.deleteErrorLogById,
  deleteErrorLogByQuery: mainFunctions.deleteErrorLogByQuery,
  // SloEvent Db Object
  createSloEvent: mainFunctions.createSloEvent,
  getIdListOfSloEventByField: mainFunctions.getIdListOfSloEventByField,
  getSloEventById: mainFunctions.getSloEventById,
  getSloEventAggById: mainFunctions.getSloEventAggById,
  getSloEventListByQuery: mainFunctions.getSloEventListByQuery,
  getSloEventStatsByQuery: mainFunctions.getSloEventStatsByQuery,
  getSloEventByQuery: mainFunctions.getSloEventByQuery,
  updateSloEventById: mainFunctions.updateSloEventById,
  updateSloEventByIdList: mainFunctions.updateSloEventByIdList,
  updateSloEventByQuery: mainFunctions.updateSloEventByQuery,
  deleteSloEventById: mainFunctions.deleteSloEventById,
  deleteSloEventByQuery: mainFunctions.deleteSloEventByQuery,
  // AuditLog Db Object
  createAuditLog: mainFunctions.createAuditLog,
  getIdListOfAuditLogByField: mainFunctions.getIdListOfAuditLogByField,
  getAuditLogById: mainFunctions.getAuditLogById,
  getAuditLogAggById: mainFunctions.getAuditLogAggById,
  getAuditLogListByQuery: mainFunctions.getAuditLogListByQuery,
  getAuditLogStatsByQuery: mainFunctions.getAuditLogStatsByQuery,
  getAuditLogByQuery: mainFunctions.getAuditLogByQuery,
  updateAuditLogById: mainFunctions.updateAuditLogById,
  updateAuditLogByIdList: mainFunctions.updateAuditLogByIdList,
  updateAuditLogByQuery: mainFunctions.updateAuditLogByQuery,
  deleteAuditLogById: mainFunctions.deleteAuditLogById,
  deleteAuditLogByQuery: mainFunctions.deleteAuditLogByQuery,
  // Alert Db Object
  createAlert: mainFunctions.createAlert,
  getIdListOfAlertByField: mainFunctions.getIdListOfAlertByField,
  getAlertById: mainFunctions.getAlertById,
  getAlertAggById: mainFunctions.getAlertAggById,
  getAlertListByQuery: mainFunctions.getAlertListByQuery,
  getAlertStatsByQuery: mainFunctions.getAlertStatsByQuery,
  getAlertByQuery: mainFunctions.getAlertByQuery,
  updateAlertById: mainFunctions.updateAlertById,
  updateAlertByIdList: mainFunctions.updateAlertByIdList,
  updateAlertByQuery: mainFunctions.updateAlertByQuery,
  deleteAlertById: mainFunctions.deleteAlertById,
  deleteAlertByQuery: mainFunctions.deleteAlertByQuery,
};
