const postFunctions = require("./post");
const commentFunctions = require("./comment");
const voteFunctions = require("./vote");
const pollOptionFunctions = require("./pollOption");
const postMediaFunctions = require("./postMedia");

module.exports = {
  // main Database
  // Post Db Object
  dbGetPost: postFunctions.dbGetPost,
  dbCreatePost: postFunctions.dbCreatePost,
  dbUpdatePost: postFunctions.dbUpdatePost,
  dbDeletePost: postFunctions.dbDeletePost,
  dbListPosts: postFunctions.dbListPosts,
  createPost: postFunctions.createPost,
  getIdListOfPostByField: postFunctions.getIdListOfPostByField,
  getPostById: postFunctions.getPostById,
  getPostAggById: postFunctions.getPostAggById,
  getPostListByQuery: postFunctions.getPostListByQuery,
  getPostStatsByQuery: postFunctions.getPostStatsByQuery,
  getPostByQuery: postFunctions.getPostByQuery,
  updatePostById: postFunctions.updatePostById,
  updatePostByIdList: postFunctions.updatePostByIdList,
  updatePostByQuery: postFunctions.updatePostByQuery,
  deletePostById: postFunctions.deletePostById,
  deletePostByQuery: postFunctions.deletePostByQuery,
  // Comment Db Object
  dbGetComment: commentFunctions.dbGetComment,
  dbCreateComment: commentFunctions.dbCreateComment,
  dbUpdateComment: commentFunctions.dbUpdateComment,
  dbDeleteComment: commentFunctions.dbDeleteComment,
  dbListComments: commentFunctions.dbListComments,
  createComment: commentFunctions.createComment,
  getIdListOfCommentByField: commentFunctions.getIdListOfCommentByField,
  getCommentById: commentFunctions.getCommentById,
  getCommentAggById: commentFunctions.getCommentAggById,
  getCommentListByQuery: commentFunctions.getCommentListByQuery,
  getCommentStatsByQuery: commentFunctions.getCommentStatsByQuery,
  getCommentByQuery: commentFunctions.getCommentByQuery,
  updateCommentById: commentFunctions.updateCommentById,
  updateCommentByIdList: commentFunctions.updateCommentByIdList,
  updateCommentByQuery: commentFunctions.updateCommentByQuery,
  deleteCommentById: commentFunctions.deleteCommentById,
  deleteCommentByQuery: commentFunctions.deleteCommentByQuery,
  // Vote Db Object
  dbGetVote: voteFunctions.dbGetVote,
  dbCreateVote: voteFunctions.dbCreateVote,
  dbUpdateVote: voteFunctions.dbUpdateVote,
  dbDeleteVote: voteFunctions.dbDeleteVote,
  dbListVotes: voteFunctions.dbListVotes,
  createVote: voteFunctions.createVote,
  getIdListOfVoteByField: voteFunctions.getIdListOfVoteByField,
  getVoteById: voteFunctions.getVoteById,
  getVoteAggById: voteFunctions.getVoteAggById,
  getVoteListByQuery: voteFunctions.getVoteListByQuery,
  getVoteStatsByQuery: voteFunctions.getVoteStatsByQuery,
  getVoteByQuery: voteFunctions.getVoteByQuery,
  updateVoteById: voteFunctions.updateVoteById,
  updateVoteByIdList: voteFunctions.updateVoteByIdList,
  updateVoteByQuery: voteFunctions.updateVoteByQuery,
  deleteVoteById: voteFunctions.deleteVoteById,
  deleteVoteByQuery: voteFunctions.deleteVoteByQuery,
  // PollOption Db Object
  dbGetPolloption: pollOptionFunctions.dbGetPolloption,
  dbCreatePolloption: pollOptionFunctions.dbCreatePolloption,
  dbUpdatePolloption: pollOptionFunctions.dbUpdatePolloption,
  dbDeletePolloption: pollOptionFunctions.dbDeletePolloption,
  dbListPolloptions: pollOptionFunctions.dbListPolloptions,
  createPollOption: pollOptionFunctions.createPollOption,
  getIdListOfPollOptionByField:
    pollOptionFunctions.getIdListOfPollOptionByField,
  getPollOptionById: pollOptionFunctions.getPollOptionById,
  getPollOptionAggById: pollOptionFunctions.getPollOptionAggById,
  getPollOptionListByQuery: pollOptionFunctions.getPollOptionListByQuery,
  getPollOptionStatsByQuery: pollOptionFunctions.getPollOptionStatsByQuery,
  getPollOptionByQuery: pollOptionFunctions.getPollOptionByQuery,
  updatePollOptionById: pollOptionFunctions.updatePollOptionById,
  updatePollOptionByIdList: pollOptionFunctions.updatePollOptionByIdList,
  updatePollOptionByQuery: pollOptionFunctions.updatePollOptionByQuery,
  deletePollOptionById: pollOptionFunctions.deletePollOptionById,
  deletePollOptionByQuery: pollOptionFunctions.deletePollOptionByQuery,
  // PostMedia Db Object
  dbGetPostmedia: postMediaFunctions.dbGetPostmedia,
  dbAddPostmedia: postMediaFunctions.dbAddPostmedia,
  dbUpdatePostmedia: postMediaFunctions.dbUpdatePostmedia,
  dbDeletePostmedia: postMediaFunctions.dbDeletePostmedia,
  dbListPostmedia: postMediaFunctions.dbListPostmedia,
  createPostMedia: postMediaFunctions.createPostMedia,
  getIdListOfPostMediaByField: postMediaFunctions.getIdListOfPostMediaByField,
  getPostMediaById: postMediaFunctions.getPostMediaById,
  getPostMediaAggById: postMediaFunctions.getPostMediaAggById,
  getPostMediaListByQuery: postMediaFunctions.getPostMediaListByQuery,
  getPostMediaStatsByQuery: postMediaFunctions.getPostMediaStatsByQuery,
  getPostMediaByQuery: postMediaFunctions.getPostMediaByQuery,
  updatePostMediaById: postMediaFunctions.updatePostMediaById,
  updatePostMediaByIdList: postMediaFunctions.updatePostMediaByIdList,
  updatePostMediaByQuery: postMediaFunctions.updatePostMediaByQuery,
  deletePostMediaById: postMediaFunctions.deletePostMediaById,
  deletePostMediaByQuery: postMediaFunctions.deletePostMediaByQuery,
};
